Repository acuarica/evm, pull requests merged in 2024-09, with the labels that each got.

#135 Invalidate memory range after `CALL`, `CALLCODE`, `DELEGATECALL` and `STATICCALL`
  README.md
  examples/Decode-Bytecode-into-Opcodes.mjs
  examples/Decompile-a-Contract.mjs
  examples/Detect-Functions-Events-ERCs.mjs
  src/state.ts
  src/step.ts
  test/__snapshots__/contracts/memory/invalidate-memory-args.snap.md
  test/__snapshots__/examples.snap.md
  test/__snapshots__/mainnet.snap.md
  test/__snapshots__/mainnet/BeaconDeposit.dis
  test/__snapshots__/mainnet/Contract.dis
  test/__snapshots__/mainnet/CryptoKitties.dis
  test/__snapshots__/mainnet/DAI.dis
  test/__snapshots__/mainnet/DAI.sol
  test/__snapshots__/mainnet/FundraisingGaugeFx.sol
  test/__snapshots__/mainnet/OmniMerlin.dis
  test/__snapshots__/mainnet/OmniMerlin.sol
  test/__snapshots__/mainnet/RankedAuctionWETHGateway.dis
  test/__snapshots__/mainnet/RankedAuctionWETHGateway.sol
  test/__snapshots__/mainnet/UnicornToken.sol
  test/contracts.test.ts
  test/examples.test.ts
  test/state.test.ts
Labels: feature

#136 Fix invalidate memory range too big
  .mocharc.yaml
  README.md
  examples/Decompile-a-Contract.mjs
  examples/Detect-Functions-Events-ERCs.mjs
  examples/State-Hook.mts
  scripts/mock.mjs
  src/index.ts
  src/state.ts
  test/__snapshots__/bin.snap.md
  test/__snapshots__/examples.snap.md
  test/bin.test.ts
  test/evm.test.ts
  test/examples.test.ts
  test/exprs.test.ts
  test/mainnet/GovernanceRouter-0x16A2D238d35e51Dd41Cf101dbb536E2cb9E233DA.bytecode
  test/state.test.ts
  test/step.test.ts
Labels: bug

#137 Include Node 22 in CI
  .github/workflows/main.yml
  scripts/4bytedb/events.json
  scripts/mock.mjs
  test/examples.test.ts
Labels: build

#139 Use `fetch` instead of custom get for http requests in `solc`
  .c8rc.json
  .mocharc.yaml
  README.md
  package.json
  scripts/solc.mjs
  test/bin.test.ts
  test/examples.test.ts
  test/exprs.test.ts
  test/scripts/mock.mjs
  test/scripts/solc.mjs
Labels: test

#140 Fix error when `BigInt` is out of range for `SHL` and `EXP`
  src/ast/alu.ts
  test/evm.test.ts
  test/mainnet.test.ts
Labels: bug

#141 Refactor `::mainnet` tests to load test data from `test/mainnet`
  test/4byte.test.ts
  test/__snapshots__/bin.snap.md
  test/__snapshots__/examples.snap.md
  test/__snapshots__/mainnet.snap.md
  test/__snapshots__/mainnet/GovernanceRouter.dis
  test/__snapshots__/mainnet/GovernanceRouter.sol
  test/mainnet.test.ts
  test/mainnet/BeaconDeposit-0x00000000219ab540356cBB839Cbe05303d7705Fa.bytecode
  test/mainnet/BeaconDeposit-0x00000000219ab540356cBB839Cbe05303d7705Fa.json
  test/mainnet/Compound-0x3FDA67f7583380E67ef93072294a7fAc882FD7E7.bytecode
  test/mainnet/Compound-0x3FDA67f7583380E67ef93072294a7fAc882FD7E7.json
  test/mainnet/Contract-0x60d20e0150F3A9717A7cb50d3F617Ebf6D953467.bytecode
  test/mainnet/Contract-0x60d20e0150F3A9717A7cb50d3F617Ebf6D953467.json
  test/mainnet/CryptoKitties-0x06012c8cf97BEaD5deAe237070F9587f8E7A266d.bytecode
  test/mainnet/CryptoKitties-0x06012c8cf97BEaD5deAe237070F9587f8E7A266d.json
  test/mainnet/DAI-0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.bytecode
  test/mainnet/DAI-0x89d24A6b4CcB1B6fAA2625fE562bDD9a23260359.json
  test/mainnet/Disperse-0x000000000049f44766dc8540e40a2ed29b636319.bytecode
  test/mainnet/Disperse-0x000000000049f44766dc8540e40a2ed29b636319.json
  test/mainnet/ENS-0x314159265dD8dbb310642f98f50C066173C1259b.bytecode
  test/mainnet/ENS-0x314159265dD8dbb310642f98f50C066173C1259b.json
  test/mainnet/FundraisingGaugeFx-0x28ED637C5e3371c2678C2d346dF04Fb634ED832d.bytecode
  test/mainnet/FundraisingGaugeFx-0x28ED637C5e3371c2678C2d346dF04Fb634ED832d.json
  test/mainnet/GovernanceRouter-0x16A2D238d35e51Dd41Cf101dbb536E2cb9E233DA.bytecode
  test/mainnet/GovernanceRouter-0x16A2D238d35e51Dd41Cf101dbb536E2cb9E233DA.json
  test/mainnet/Leverage-0x13df570de8465f5319b6a2c60de21716400074e7.bytecode
  test/mainnet/Leverage-0x13df570de8465f5319b6a2c60de21716400074e7.json
  test/mainnet/MSOW-0x07880D44b0f7b75464ad18fc2b980049c40A8bc3.bytecode
  test/mainnet/MSOW-0x07880D44b0f7b75464ad18fc2b980049c40A8bc3.json
  test/mainnet/MobyToken-0x40a7dF3dF8b56147B781353D379cB960120211D7.bytecode
  test/mainnet/MobyToken-0x40a7dF3dF8b56147B781353D379cB960120211D7.json
  test/mainnet/OmniMerlin-0x234F534D322dF1a8a236a2F952d6657bf800F1FA.bytecode
  test/mainnet/OmniMerlin-0x234F534D322dF1a8a236a2F952d6657bf800F1FA.json
  test/mainnet/ProxyForCoinTool-0x00000df4e8ed07e76c4d279e9937033cd555fad3.bytecode
  test/mainnet/ProxyForCoinTool-0x00000df4e8ed07e76c4d279e9937033cd555fad3.json
  test/mainnet/RankedAuctionWETHGateway-0x47b24fDF2f8EC7b72ac879b124F90f3FC53b51cA.bytecode
  test/mainnet/RankedAuctionWETHGateway-0x47b24fDF2f8EC7b72ac879b124F90f3FC53b51cA.json
  test/mainnet/SEAWHALE-0x9DD0fEcBAa5D12948f522F17dedE8B599448Fbbe.bytecode
  test/mainnet/SEAWHALE-0x9DD0fEcBAa5D12948f522F17dedE8B599448Fbbe.json
  test/mainnet/SHA1Digest-0x9c9fcEa62bD0A723b62A2F1e98dE0Ee3df813619.bytecode
  test/mainnet/SHA1Digest-0x9c9fcEa62bD0A723b62A2F1e98dE0Ee3df813619.json
  test/mainnet/SmithBotExecutor-0x000000000000Df8c944e775BDe7Af50300999283.bytecode
  test/mainnet/SmithBotExecutor-0x000000000000Df8c944e775BDe7Af50300999283.json
  test/mainnet/USDC-0x5425890298aed601595a70AB815c96711a31Bc65.bytecode
  test/mainnet/USDC-0x5425890298aed601595a70AB815c96711a31Bc65.json
  test/mainnet/UnicornToken-0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7.bytecode
  test/mainnet/UnicornToken-0x89205A3A3b2A69De6Dbf7f01ED13B2108B2c43e7.json
  test/mainnet/VotingEscrowDelegationProxy-0x9B12C90BAd388B7e417271eb20678D1a7759507c.bytecode
  test/mainnet/VotingEscrowDelegationProxy-0x9B12C90BAd388B7e417271eb20678D1a7759507c.json
  test/mainnet/WETH-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.bytecode
  test/mainnet/WETH-0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2.json
  test/mainnet/big_game-0xe29945D03AE99e8fa285F0D53e72C7C04567A5fB.bytecode
  test/mainnet/big_game-0xe29945D03AE99e8fa285F0D53e72C7C04567A5fB.json
  test/scripts/mock.mjs
Labels: test

#142 Add contract test for `bigint` out of range
  src/ast/alu.ts
  test/__snapshots__/mainnet.snap.md
  test/__snapshots__/mainnet/Math.dis
  test/mainnet/GovernanceRouter-0x16A2D238d35e51Dd41Cf101dbb536E2cb9E233DA.json
  test/mainnet/Math-0xa4846160bdcd18f9de4d434d09399bc6f6231fa4.json
Labels: test

#143 Rename GitHub workflows to be more declarative
  .github/workflows/gh-pages.yml
  .github/workflows/gh-release.yml
  .github/workflows/npm-publish.yml
  .github/workflows/pr-dataset-test.yml
  .github/workflows/pr-size-limit.yml
  .github/workflows/test.yml
Labels: build, refactor

#144 Fix typo in description for option flag `--with-trace` in `sevm` CLI
  README.md
  bin/sevm.mjs
Labels: docs

#146 Include error instead of `throw`ing when reaching a non-`halted` state
  src/evm.ts
  test/__snapshots__/mainnet.snap.md
  test/__snapshots__/mainnet/ZapStEth.dis
  test/__snapshots__/mainnet/ZapStEth.sol
  test/evm.test.ts
  test/mainnet/ZapStEth-0x4a7B05aEf57516A0C181d3108437dEC2CD0a6cfd.json
Labels: feature
